apiVersion: apps.rumraisin.me/v1
kind: MysqlCluster
metadata:
  labels:
    app.kubernetes.io/name: mysql-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysqlcluster-sample
spec:
  # TODO(user): Add fields here
